apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ml-api
  name: ml-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ml-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ml-api
    spec:
      containers:
      - args:
        - bash
        - -c
        - gunicorn --bind 0.0.0.0:3333 --workers 1 wsgi
        env:
        - name: DEBUG
          value: "True"
        - name: FLASK_APP
          value: server.py
        image: thespaghettidetective/ml_api:base-1.1
        imagePullPolicy: ""
        name: ml-api
        resources: {}
      hostname: ml-api
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
