apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - sh
        - -c
        - python manage.py collectstatic --noinput && python manage.py migrate &&
          python manage.py runserver --noreload 0.0.0.0:3334
        env:
        - name: ACCOUNT_ALLOW_SIGN_UP
          value: "False"
        - name: DATABASE_URL
          value: sqlite:////app/db.sqlite3
        - name: DEBUG
          value: "False"
        - name: DEFAULT_FROM_EMAIL
          value: ""
        - name: EMAIL_HOST
          value: ""
        - name: EMAIL_HOST_PASSWORD
        - name: EMAIL_HOST_USER
        - name: EMAIL_PORT
          value: "25"
        - name: EMAIL_USE_TLS
          value: "False"
        - name: INTERNAL_MEDIA_HOST
          value: http://web:3334
        - name: ML_API_HOST
          value: http://ml-api:3333
        - name: REDIS_URL
          value: redis://redis:6379
        - name: SITE_IS_PUBLIC
          value: "False"
        - name: SITE_USES_HTTPS
          value: "True"
        - name: SOCIAL_LOGIN
          value: "False"
        - name: WEBPACK_LOADER_ENABLED
          value: "False"
        image: ghcr.io/balazsborbely/tsd-web:latest
        imagePullPolicy: ""
        name: web
        ports:
        - containerPort: 3334
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: web-claim0
      hostname: web
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
status: {}
